apiVersion: odigos.io/v1alpha1
kind: Destination
metadata:
  name: dynatrace
  namespace: odigos-system
spec:
  data:
    DYNATRACE_URL: DT_TENANT_URL
  secretRef:
    name: dynatrace
  signals:
    - TRACES
    - METRICS
    - LOGS
  type: dynatrace